### ISSUE TITLE
Interactive mode is glitchy on windows regarding whitespace, there's a 10 space wide gap

### ISSUE THREAD

**Issue by Boscop** [fuyufjh/heygpt#10]
When I start it on Windows in interactive mode, there is a bunch of whitespace between > and my cursor:
![image](https://user-images.githubusercontent.com/535593/232243986-49ddfbae-1177-4c8c-a19c-3ed96a36d4cb.png)

When I start typing, it appends the chars at the cursor but when I press backspace at some point, it "un-indents" the prompt, but now there is a gap in the middle of the prompt!
![image](https://user-images.githubusercontent.com/535593/232244503-bbf43e24-3511-4616-bcc0-ee043a3c7cce.png)

When I type more, it appends at the end, but when I press backspace again, it shifts the whitespace gap to be directly before the cursor. This gap seems to be always 10 spaces wide:
![image](https://user-images.githubusercontent.com/535593/232244716-c955e172-c074-4f0e-88ae-af475db43a5d.png)

Also initially:
![image](https://user-images.githubusercontent.com/535593/232244835-eae257af-ecce-4ecb-865c-cac534a38659.png)

**Comment by fuyufjh** [comment]
Might be an issue of the Terminal Emulator. Which one are you using? Windows Terminal or Mintty or else?
