### ISSUE TITLE
 assistant => Error: EventSource stream error: Invalid status code: 400 Bad Request exit 1

### ISSUE THREAD

**Issue by deadjoe** [fuyufjh/heygpt#3]
Thanks for this awesome project and it works super fast  and lightweight. 
Just found an error occurs several times as below and subject:
"assistant => Error: EventSource stream error: Invalid status code: 400 Bad Request exit 1"
and the program will be quit after the above error, the way to solve it is just launch the program again.

btw: My network is stable and confirmed no problem when the error occurred.

**Comment by fuyufjh** [comment]
This error is from the server-side. Today I've also found the API service of OpenAI seems quite unstable.

But I agree that we should handle this error in a better way, rather than quiting immediately. I'll try to fix it.

**Comment by fuyufjh** [comment]
Now it will print and error and allows you to continue the conversation.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/10192522/223736258-72ee4085-42b7-4dab-895f-2f9d97ec1111.png">

**Comment by fuyufjh** [comment]
> i have pull the new code and rebuilt the app but no luck still got the problem as below: <img alt="image" width="1620" src="https://user-images.githubusercontent.com/2519527/223967033-becc6f3a-9318-4016-a339-5fe4fce408b6.png">
> 
> still need to quit the current interactive conversation prompt and re-launch the appliction.

When the input length exceeds the max token, a 400 error will be returned.

If that's not the case, can you please post the input here? So that I can try to reproduce it.
