### ISSUE TITLE
429 too many requests for first question

### ISSUE THREAD

**Issue by ravecat** [fuyufjh/heygpt#8]
Hi! I decided to try the heygpt and faced with error. Is there any debugging mode?

<img width="581" alt="image" src="https://user-images.githubusercontent.com/24782863/231872239-8c0efe18-4702-4fa9-b844-891344b26e4d.png">

**Comment by ravecat** [comment]
I figured out what the problem is, the chat subscription and the API subscription aren't linked. took the subscription and it worked

**Comment by qaohv** [comment]
Hi, @ravecat , I faced the same error but didn't get how you fixed it. Please, could you explain it clearly?

**Comment by ravecat** [comment]
> Hi, @ravecat , I faced the same error but didn't get how you fixed it. Please, could you explain it clearly?

@qaohv after subscribing to the paid API this error disappeared, your [account](https://platform.openai.com/account/billing/overview) looks like (see, "cancel paid account" button )

<img width="894" alt="image" src="https://user-images.githubusercontent.com/24782863/233396760-f5e71256-b013-4ae0-9181-ef257fb3623a.png">

but it's my case maybe you have another root

**Comment by qaohv** [comment]
Thanks for clarification!
