### ISSUE TITLE
Doesn't work with command result substitution as expected

### ISSUE THREAD

**Issue by ravecat** [fuyufjh/heygpt#9]
Hello! Thank you for tool! Try to to work with command result (example below contains command from README), it doesn't work as expected. `heygpt` try ti explain bash command instead of command result

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/24782863/231879656-e1442093-6799-4cbf-894b-3ac5f4a35cf6.png">

**Comment by ravecat** [comment]
Sorry, understood. Substituion availbale inside bash environment, not in dialog with openai

**Comment by fuyufjh** [comment]
Correct. heygpt won't do anything for the input. It's just bash trick
